Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,13 +18,14 @@ jobs:
         uses: actions/checkout@v4
 
       # =========================
-      # STAGE 2: SONARQUBE SCAN
+      # STAGE 2: SONARCLOUD SCAN
       # =========================
-      - name: SonarQube Code Quality Scan
+      - name: SonarCloud Code Quality Scan
         uses: SonarSource/sonarcloud-github-action@v2
         env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
         with:
+          projectBaseDir: .
           args: >
             -Dsonar.projectKey=Vivaanjain02_Devops
             -Dsonar.organization=vivaanjain02
@@ -38,16 +39,25 @@ jobs:
           docker build -t devops-static-app .
 
       # =========================
-      # STAGE 4: RUN + TEST
+      # STAGE 4: RUN + SMOKE TEST
       # =========================
       - name: Run container and smoke test
         run: |
+          docker rm -f test-app || true
           docker run -d -p 8080:80 --name test-app devops-static-app
           sleep 5
           curl -f http://localhost:8080
 
       # =========================
-      # STAGE 5: MONITORING READY
+      # STAGE 5: CLEANUP
+      # =========================
+      - name: Cleanup container
+        if: always()
+        run: |
+          docker rm -f test-app || true
+
+      # =========================
+      # STAGE 6: MONITORING READY
       # =========================
       - name: Monitoring Ready
         run: |
